### ISSUE TITLE
Build fails: textAppearance resource not found after upgrading Android support libs to 27.0.2

### ISSUE THREAD

**Issue by lirkki** [NAXAM/stripe-android-binding#3]
I took a clone of stripe-android-binding repository, upgraded the Xamarin Android Support NuGet packages in the project to version 27.0.2 and compiled. I get this error message:

`/stripe-android-binding/Demo/Demo/obj/Debug/lp/3/jl/res/layout/activity_add_source.xml(0,0): Error APT0000: No resource found that matches the given name (at 'textAppearance' with value '@style/TextAppearance.AppCompat.Notification'). (APT0000) (Demo)`

My other project depends on Naxam.Stripe.Droid Nuget package. After I upgraded Xamarin Android Support libraries from version 26.1.0.1 to version 27.0.2 in my project, the compilation fails there as well with the same error message.

So currently it seems that the project cannot upgrade their Xamarin Android Support packages to 27.0.2 if the project has a dependency to Naxam.Stripe.Droid.

**Comment by kwacks** [comment]
Same issue here

**Comment by tuyen-vuduc** [comment]
Plz don't update your Android Support to `27.0.2`. It isn't ok to use.

**Comment by kwacks** [comment]
what's the ETA for the upgrade?

**Comment by tuyen-vuduc** [comment]
@kwacks We don't have any resource right now for this.
If it's your chance to use in your project, it's worth for you to do upgrade this binding library then create a PR. 
I am very happy to do merge.

Cheers.

**Comment by tuyen-vuduc** [comment]
This issue doesn't relate to this binding library. I gonna close.

NOTE: Android Support v27x isn't ready for use at the moment. Plz don't try to upgrade.
